### ISSUE TITLE
Hagezi DoH/VPN/TOR/Proxy blocks lists

### ISSUE THREAD

**Issue by aviv926** [nextdns/dns-bypass-methods#13]
There are many deficiencies in the lists, there is a list in the name
hagezi which includes DoH/VPN/TOR/Proxy blocks and is updated very frequently
I would recommend adding it to the lists here, it would absolutely improve the dns-bypass-methods feature

Link to the list:
[https://github.com/hagezi/dns-blocklists#outbox_tray-dohvpntorproxy-bypass---prevent-methods-to-bypass-your-dns-](https://github.com/hagezi/dns-blocklists#outbox_tray-dohvpntorproxy-bypass---prevent-methods-to-bypass-your-dns-)

**Comment by romaincointepas** [comment]
Added, thanks

**Comment by aviv926** [comment]
> Added, thanks

Thanks! 
I'm guessing it can't be added visually through the blocklists but it's embedded within the Block Bypass Methods feature?

**Comment by romaincointepas** [comment]
Yep, it was added internally as one of the sources for Block Bypass Methods.

**Comment by aviv926** [comment]
> Yep, it was added internally as one of the sources for Block Bypass Methods.

Does it appear anywhere in the source code?

**Comment by aviv926** [comment]
> Yep, it was added internally as one of the sources for Block Bypass Methods.

Does it appear anywhere in the source code?
