### ISSUE TITLE
Please add hagezi's DoH/VPN/TOR/Proxy Bypass list to blocked domains under Parental Control/Block Bypass Methods methods or as a selectable list under Blocklists

### ISSUE THREAD

**Issue by remecz** [nextdns/dns-bypass-methods#7]
The default bypass domain list seems to miss many of the available VPN/proxy bypass services and doesn't seem to be regularly maintained.

https://github.com/hagezi/dns-blocklists#dohvpntorproxy-bypass---prevent-methods-to-bypass-your-dns-

**Comment by romaincointepas** [comment]
Added, thanks
